"""Initial migration: create influencers, messages, outreach_logs tables

Revision ID: bfaaf3482b28
Revises: 
Create Date: 2026-10-02 04:39:52.398549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfaaf3482b28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', name='platform'), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content_themes', sa.JSON(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('tiktok_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('audience_age', sa.String(length=50), nullable=True),
    sa.Column('audience_gender', sa.String(length=50), nullable=True),
    sa.Column('audience_geography', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'profile_url', name='uq_influencer_platform_profile'),
    sa.UniqueConstraint('profile_url')
    )
    op.create_index('ix_influencer_category', 'influencers', ['category'], unique=False)
    op.create_index('ix_influencer_contact_email', 'influencers', ['contact_email'], unique=False)
    op.create_index('ix_influencer_created_at', 'influencers', ['created_at'], unique=False)
    op.create_index('ix_influencer_follower_count', 'influencers', ['follower_count'], unique=False)
    op.create_index('ix_influencer_platform', 'influencers', ['platform'], unique=False)
    op.create_index('ix_influencer_source', 'influencers', ['source'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('instagram_dm', sa.Text(), nullable=False),
    sa.Column('personalization_signals', sa.JSON(), nullable=False),
    sa.Column('collaboration_angle', sa.Enum('SPONSORSHIP', 'AFFILIATE', 'UGC', 'AMBASSADOR', 'PLACEMENT', 'BARTER', name='collaborationangle'), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_generated_at', 'messages', ['generated_at'], unique=False)
    op.create_index('ix_message_influencer_id', 'messages', ['influencer_id'], unique=False)
    op.create_index('ix_message_prompt_version', 'messages', ['prompt_version'], unique=False)
    op.create_table('outreach_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'INSTAGRAM', name='outreachchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SIMULATED', 'SKIPPED', name='outreachstatus'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('influencer_id', 'channel', 'message_hash', name='uq_outreach_influencer_channel_hash')
    )
    op.create_index('ix_outreach_channel', 'outreach_logs', ['channel'], unique=False)
    op.create_index('ix_outreach_influencer_id', 'outreach_logs', ['influencer_id'], unique=False)
    op.create_index('ix_outreach_message_hash', 'outreach_logs', ['message_hash'], unique=False)
    op.create_index('ix_outreach_message_id', 'outreach_logs', ['message_id'], unique=False)
    op.create_index('ix_outreach_sent_at', 'outreach_logs', ['sent_at'], unique=False)
    op.create_index('ix_outreach_status', 'outreach_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outreach_status', table_name='outreach_logs')
    op.drop_index('ix_outreach_sent_at', table_name='outreach_logs')
    op.drop_index('ix_outreach_message_id', table_name='outreach_logs')
    op.drop_index('ix_outreach_message_hash', table_name='outreach_logs')
    op.drop_index('ix_outreach_influencer_id', table_name='outreach_logs')
    op.drop_index('ix_outreach_channel', table_name='outreach_logs')
    op.drop_table('outreach_logs')
    op.drop_index('ix_message_prompt_version', table_name='messages')
    op.drop_index('ix_message_influencer_id', table_name='messages')
    op.drop_index('ix_message_generated_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_influencer_source', table_name='influencers')
    op.drop_index('ix_influencer_platform', table_name='influencers')
    op.drop_index('ix_influencer_follower_count', table_name='influencers')
    op.drop_index('ix_influencer_created_at', table_name='influencers')
    op.drop_index('ix_influencer_contact_email', table_name='influencers')
    op.drop_index('ix_influencer_category', table_name='influencers')
    op.drop_table('influencers')
    # ### end Alembic commands ###
